spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: midev2112


  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: create